const groupService = require('./groupService');
const expenseService = require('./expenseService');
const balanceService = require('./balanceService');
const settlementService = require('./settlementService');
const audit = require('./auditService');
const { safeText, toLine } = require('../utils/csv');

const STATUS_LABEL = { is_owed: 'Gets back', owes: 'Owes', settled: 'Settled' };

// "Khushi 333.34; Riya 333.33" - who owes how much of this expense.
function describeSplits(expense) {
  return expense.splits
    .map((s) => {
      if (expense.split_method === 'percentage') return `${s.name} ${s.input_value}% = ${s.share}`;
      if (expense.split_method === 'custom') return `${s.name} ${s.input_value} share(s) = ${s.share}`;
      return `${s.name} ${s.share}`;
    })
    .join('; ');
}

// Reads everything once. All reads are synchronous, so the data is consistent.
function loadData(groupId) {
  const { balances, summary } = balanceService.getGroupBalances(groupId);
  return {
    // The services return newest first; a statement reads better oldest first.
    expenses: expenseService.listExpenses(groupId, { limit: 1000000, offset: 0 }).expenses.reverse(),
    payments: settlementService.listSettlements(groupId).reverse(),
    balances,
    summary,
    plan: settlementService.computeSettlementPlan(
      balances.map((b) => ({ userId: b.user_id, balanceMinor: b.balance_minor }))
    ),
  };
}

// Each section: a title, column headers, rows, and what to print when empty.
function buildSections(data) {
  const nameOf = new Map(data.balances.map((b) => [b.user_id, b.name]));

  return {
    expenses: {
      title: 'Expenses',
      header: ['ID', 'Date', 'Description', 'Category', 'Paid by', 'Amount (INR)', 'Split method', 'Split details'],
      rows: data.expenses.map((e) => [
        e.id, e.expense_date, safeText(e.description), safeText(e.category), safeText(e.paid_by.name),
        e.amount, e.split_method, safeText(describeSplits(e)),
      ]),
      empty: 'No expenses recorded',
    },
    balances: {
      title: 'Balances (positive = gets back, negative = owes)',
      header: ['Member', 'Status', 'Balance (INR)'],
      rows: data.balances.map((b) => [
        safeText(b.is_active ? b.name : `${b.name} (left the group)`), STATUS_LABEL[b.status], b.balance,
      ]),
      empty: 'No members',
    },
    payments: {
      title: 'Recorded payments',
      header: ['ID', 'Date', 'From', 'To', 'Amount (INR)', 'Note'],
      rows: data.payments.map((p) => [
        p.id, p.created_at, safeText(p.from.name), safeText(p.to.name), p.amount, safeText(p.note),
      ]),
      empty: 'No payments recorded yet',
    },
    plan: {
      title: 'Suggested settlement plan',
      header: ['From', 'To', 'Amount (INR)'],
      rows: data.plan.transfers.map((t) => [
        safeText(nameOf.get(t.fromUser)), safeText(nameOf.get(t.toUser)), require('../utils/money').formatMinor(t.amountMinor),
      ]),
      empty: 'Nothing to settle',
    },
  };
}

/*
 * section: 'all' (summary + four titled sections) or one of
 * 'expenses' | 'balances' | 'payments' | 'plan' (a single clean table).
 * Returns { filename, csv, expenseCount }.
 */
function buildStatement({ groupId, user, section }) {
  const group = groupService.getGroupDetails(groupId, user.id);
  const data = loadData(groupId);
  const sections = buildSections(data);
  const now = new Date().toISOString();
  const lines = [];

  if (section === 'all') {
    lines.push(
      toLine(['SettleNet statement']),
      toLine(['Group', safeText(group.name)]),
      toLine(['Generated at (UTC)', now]),
      toLine(['Generated by', safeText(user.name)]),
      toLine(['Members', safeText(group.members.map((m) => m.name).join('; '))]),
      toLine(['Number of expenses', data.summary.expense_count]),
      toLine(['Total spent (INR)', data.summary.total_spent])
    );
    for (const key of ['expenses', 'balances', 'payments', 'plan']) {
      const s = sections[key];
      lines.push('', toLine([s.title]), toLine(s.header));
      if (s.rows.length === 0) lines.push(toLine([s.empty]));
      s.rows.forEach((row) => lines.push(toLine(row)));
    }
  } else {
    const s = sections[section];
    lines.push(toLine(s.header));
    s.rows.forEach((row) => lines.push(toLine(row)));
  }

  audit.log({
    userId: user.id,
    groupId,
    action: audit.ACTIONS.STATEMENT_EXPORTED,
    entityType: 'group',
    entityId: groupId,
    metadata: { section, expense_count: data.summary.expense_count },
  });

  const slug = group.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'group';
  const suffix = section === 'all' ? '' : `-${section}`;
  return {
    filename: `settlenet-${slug}${suffix}-${now.slice(0, 10)}.csv`,
    // The BOM (\uFEFF) makes Excel open the file as UTF-8, so non-English names display correctly.
    csv: `\uFEFF${lines.join('\r\n')}\r\n`,
    expenseCount: data.summary.expense_count,
  };
}

module.exports = { buildStatement };
